In [3]:
import numpy as np

In [4]:
np.__version__

'1.19.2'

In [5]:
array=np.arange(1,21,1)

In [6]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
Aws2=array %2==0

In [8]:
Aws2

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [10]:
array[Aws2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
Aws3=array%3==0

In [12]:
Aws3

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [13]:
array[Aws3]

array([ 3,  6,  9, 12, 15, 18])