In [1]:
import numpy as np

In [10]:
array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1_inverse = np.linalg.inv(array1)
print("1. 反矩陣 : \n",array1_inverse,"\n")
array1_matmul=np.matmul(array1,array1_inverse)
print("乘上原矩陣 : \n",array1_matmul,"\n")
print("觀察是否為單位矩陣? : ",np.all(np.identity(2)==array1_matmul))

#運用上列array計算特徵值、特徵向量?
w,v = np.linalg.eig(array1)
print(" \n2.運用上列array計算特徵值、特徵向量?\n eigenvalue :\n",w,"\n eigenvector : \n",v)
#運用上列array計算SVD?
u,s,vh=np.linalg.svd(array1)
print(" \n3.運用上列array計算SVD?\n u :\n",u,"\n s : \n",s,"\n vh : \n",vh)

1. 反矩陣 : 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]] 

乘上原矩陣 : 
 [[1. 0.]
 [0. 1.]] 

觀察是否為單位矩陣? :  True
 
2.運用上列array計算特徵值、特徵向量?
 eigenvalue :
 [13.  2.] 
 eigenvector : 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]
 
3.運用上列array計算SVD?
 u :
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
 s : 
 [13.94721714  1.86417116] 
 vh : 
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
