In [1]:
import numpy as np

In [6]:
alist = [[1,2,3],[5,6,7],[8,9,10]]

In [8]:
alist

[[1, 2, 3], [5, 6, 7], [8, 9, 10]]

In [9]:
ar1 = np.array(alist)

In [10]:
ar1

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
ar1.flatten()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [12]:
ar1

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [13]:
ar1.ravel()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [15]:
for row in ar1:
    print(row)

[1 2 3]
[5 6 7]
[ 8  9 10]


In [16]:
array1 = np.array(range(30))

In [17]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
Aws1= array1.reshape(5,6)

In [20]:
Aws1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [22]:
np.where(Aws1%6 == 1)

NameError: name 'Aws' is not defined