In [1]:
import numpy as np
with open('one_array.npy','wb') as f:
    np.save(f,np.array([1,2]))

In [2]:
np.load('one_array.npy')

array([1, 2])

In [20]:
from io import StringIO

data = u" 20  51  332  3  4 "
np.genfromtxt(StringIO(data), delimiter=3)

array([ 20.,   5.,   1., 332.,   3.,   4.,  nan])

In [29]:
a = u"1,2,3,4,5\n6,7,8,9,10"
np.genfromtxt(StringIO(a), delimiter=",", names="a, b, c", usecols=("b", "c"))

array([(2., 3.), (7., 8.)], dtype=[('b', '<f8'), ('c', '<f8')])

In [33]:
a = u"1 2 3 4 5\n6 7 8 9 10"
np.genfromtxt(StringIO(a), usecols=(1, -1))

array([[ 2.,  5.],
       [ 7., 10.]])